---
# tasks file for shiva
- name: install apache2
  apt: 
   name: apache2
   state: present
- name: copy file
  copy:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0777'
